const words = [
  { word: "б_рёза", answers: ["е"], fullWord: "берёза" },
  { word: "в_р_бей", answers: ["о", "о"], fullWord: "воробей" },
  { word: "Б_л_русь", answers: ["е", "а"], fullWord: "Беларусь" },
  { word: "сах_р", answers: ["а"], fullWord: "сахар" },
  { word: "в_гон", answers: ["а"], fullWord: "вагон" },
  { word: "в_рона", answers: ["о"], fullWord: "ворона" },
  { word: "в_скр_сен_е", answers: ["о", "е", "ь"], fullWord: "воскресенье" },
  { word: "вч_ра", answers: ["е"], fullWord: "вчера" },
  { word: "гор_д", answers: ["о"], fullWord: "город" },
  { word: "д_журный", answers: ["е"], fullWord: "дежурный" },
  { word: "д_кабрь", answers: ["е"], fullWord: "декабрь" },
  { word: "д_рога", answers: ["о"], fullWord: "дорога" },
  { word: "з_ря_ка", answers: ["а", "д"], fullWord: "зарядка" },
  { word: "за_ц", answers: ["я"], fullWord: "заяц" },
  { word: "к_никулы", answers: ["а"], fullWord: "каникулы" },
  { word: "к_р_ндаш", answers: ["а", "а"], fullWord: "карандаш" },
  {
    word: "б_л_ру__кий",
    answers: ["е", "о", "с", "с"],
    fullWord: "белорусский",
  },
  { word: "м_л_ко", answers: ["о", "о"], fullWord: "молоко" },
  { word: "кла__", answers: ["с", "с"], fullWord: "класс" },
  { word: "комн_та", answers: ["а"], fullWord: "комната" },
  { word: "к_не_но", answers: ["о", "ч"], fullWord: "конечно" },
  { word: "к_рова", answers: ["о"], fullWord: "корова" },
  { word: "м_г_зин", answers: ["а", "а"], fullWord: "магазин" },
  { word: "мал_нький", answers: ["е"], fullWord: "маленький" },
  { word: "мес_ц", answers: ["я"], fullWord: "месяц" },
  { word: "м_рко_ь", answers: ["о", "в"], fullWord: "морковь" },
  { word: "м_ро_", answers: ["о", "з"], fullWord: "мороз" },
  { word: "н_ябрь", answers: ["о"], fullWord: "ноябрь" },
  { word: "_г_род", answers: ["о", "о"], fullWord: "огород" },
  { word: "_ктябрь", answers: ["о"], fullWord: "октябрь" },
  { word: "п_года", answers: ["о"], fullWord: "погода" },
  { word: "п_м_дор", answers: ["о", "и"], fullWord: "помидор" },
  { word: "р_бята", answers: ["е"], fullWord: "ребята" },
  { word: "Род_на", answers: ["и"], fullWord: "Родина" },
  { word: "с_нтябрь", answers: ["е"], fullWord: "сентябрь" },
  { word: "с_л_вей", answers: ["о", "о"], fullWord: "соловей" },
  { word: "с_рока", answers: ["о"], fullWord: "сорока" },
  { word: "учит_ль", answers: ["е"], fullWord: "учитель" },
  { word: "х_р_шо", answers: ["о", "о"], fullWord: "хорошо" },
  { word: "ябл_к_", answers: ["о", "о"], fullWord: "яблоко" },
  { word: "яг_да", answers: ["о"], fullWord: "ягода" },
  { word: "_зык", answers: ["я"], fullWord: "язык" },
];
